language: bash
services: docker

env:
  - VERSION=11
  - VERSION=11 VARIANT=slim
  - VERSION=10
  - VERSION=10 VARIANT=slim
  - VERSION=8
  - VERSION=8 VARIANT=slim
  - VERSION=8 VARIANT=alpine
  - VERSION=7
  - VERSION=7 VARIANT=slim
  - VERSION=7 VARIANT=alpine

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - env | sort
  - cd "$VERSION"
  - imageBase="openjdk:$VERSION"
  - imageSuffix="${VARIANT:+-$VARIANT}"

script:
  - |
    (
      set -Eeuo pipefail
      set -x
      travis_retry docker build -t "$imageBase-jdk$imageSuffix" "jdk${VARIANT:+/$VARIANT}"
      travis_retry docker build -t "$imageBase-jre$imageSuffix" "jre${VARIANT:+/$VARIANT}"
      ~/official-images/test/run.sh "$imageBase-jdk$imageSuffix" "$imageBase-jre$imageSuffix"
    )

after_script:
  - docker images

# vim:set et ts=2 sw=2:
